### PR TITLE
#9 Adding basic equation processing for toggle buttons

### PR DESCRIPTION
**Pull request by rmroc451**

### CODE REVIEW

**Comment by nguyenquyhy** [comment]
I am terribly sorry that in order to facilitate the expression evaluation, I did some refactoring to move all evaluation logic into IEvaluator interface, and that create quite a conflict with your PR.

Do you want to rebase your PR commit on top of that? The design is quite simple, just need to create a new Evaluator and move your logic into the 2 functions. You can reference the SimpleEvaluator, which encapsulates current logic. 
GenericToggleAction should be unchanged.

If you are busy, I can do the integration for you too.

**Comment by rmroc451** [comment]
If you can get to it now, that is totally fine with me.  It's family time now :)

Otherwise, I'll get to it tomorrow on my lunch break :)

**Comment by nguyenquyhy** [comment]
I still have some time today, so I'll sort this out. Thanks for the PR.

**Comment by rmroc451** [comment]
Np! I'm happy to help with some of the other issues too. If you want to assign me the variables allowed in the gauge action, I can do that tomorrow.

I'm trying to think how to best not step on each other's toes with duplicating work :)

Maybe we just look at the other's branches, before picking it up?

**Comment by nguyenquyhy** [comment]
Manually merged at 266bf9fd4b0e2c5012bd66e66af41ce04942f85c.

About not overlapping work, do you use Discord? I am Hy in the official MSFS Discord, maybe we can discuss a bit.

**Pull request closed without merging**
