### PR TITLE
114 - add ability to embed/change background on nav/com button

### PR DESCRIPTION
**Pull request by rmroc451**
also protect against large images.

### CODE REVIEW

**Comment by rmroc451** [comment]
closes #114

**Comment by nguyenquyhy** [comment]
I'm still not too sure about different weight and size of the header though. Make it feel weird when sitting with other buttons (feel a bit like 2 different plugins).

I'm thinking of following other preset buttons: allowing user to hide the header so they can just put whatever they want in the background (which they now can with this PR 😄).

Also I don't like the current alignment very much. It feel off to the right, but not right aligned either.
image
I think I'll make some adjustment there too.

**Comment by rmroc451** [comment]
I'm good with your recommendations. Was just trying to keep the settings page succinct, like you like :)

Feel free to undo the styling and keep the background stuff. :)

**Comment by nguyenquyhy** [comment]
Close for now as I have manually merged the background support. I wish GitHub has "Close as merged" though.

**Pull request closed without merging**
